import './globals.css'



export const metadata: Metadata = {
  title: 'Trello Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-slate-100'>{children}</body>
    </html>
  )
}
